name: Build and Release Plugin

on:
  push:
    tags:
      - 'v*'

# 添加权限配置
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew buildPlugin

      - name: Find zip file
        id: find_zip
        run: |
          ZIP_FILE=$(find ./build/distributions -name "*.zip" | head -n 1)
          if [ -z "$ZIP_FILE" ]; then
            echo "No zip file found in build/distributions"
            exit 1
          fi
          echo "Found zip file: $ZIP_FILE"
          echo "zip_file=$ZIP_FILE" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.find_zip.outputs.zip_file }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 